# Generated by Django 5.1.6 on 2025-02-25 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countries.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
